### ISSUE TITLE
Support separate status and kill endpoints

### ISSUE THREAD

**Issue by toothbrush** [monzo/envoy-preflight#6]
Normally, `envoy-preflight` expects that before startup, it can poll the admin endpoint for proxy status, then run the process, and finally hit the same admin endpoint with POST to `/quitquitquit` to finalise and shutdown.

On Istio, this approach fails.  Istio runs a thing called `pilot-agent` which bootstraps and wraps the Envoy proxy sidecar.  When one directly hits the kill endpoint on Envoy, Envoy quits, but pilot-agent just restarts it, defeating the object.  

Since Istio 1.3.0, pilot-agent [supports a `/quitquitquit` endpoint](https://github.com/istio/istio/issues/15041), too.

I think the simplest approach to solve this issue would be something like optional separate configuration of the kill-endpoint in `envoy-preflight`.  For example, apart from the `ENVOY_ADMIN_API` variable, perhaps also have an optional `ENVOY_QUIT_ENDPOINT_API` (better name would be useful), for those running Istio.

**Comment by jackkleeman** [comment]
@toothbrush I think that `ENVOY_KILL_API` could work!
There is also a new health check envoy endpoint we could use to avoid json parsing at some point

**Comment by toothbrush** [comment]
Would be happy to help, although i see you beat me to it 😃 thanks!
